application: phus-bot
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*\.py
  script: wsgi.app
  secure: optional

- url: /_ah/xmpp/message/chat/
  script: wsgi.app

inbound_services:
- xmpp_message

